title: ì•„ë¬´íŠ¼ í•´ë³´ì ê°œë°œê³µë¶€
author: ghkdusghd
email: yeonguo95@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  ğŸ‘©ğŸ»â€ğŸ’» ê³µë¶€í•˜ëŠ” í•™ìƒ ê°œë°œì
show_excerpts: true # set to true to show excerpts on the homepage
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Hwayeon Hong
  tagline: Developer
  date_format: "%b %-d, %Y"
  disqus_shortname: games
  analytics_id: "yeonguo95"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/profile_image.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "kr" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  navigation:
    - title: Projects
      url: "/projects/"
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    # twitter: samarsault
    github: ghkdusghd
    # linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: yeonguo95@gmail.com

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

baseurl: ""
url: "https://ghkdusghd.github.io"
